# Generated by Django 6.0.1 on 2026-01-31 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='otp_created_at',
        ),
    ]
