# Generated by Django 6.0.1 on 2026-02-07 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='course_name',
            field=models.CharField(choices=[('AIML', 'Artificial Intelligence and Machine Learning'), ('CORE', 'Computer Science Core'), ('IT', 'Information Technology'), ('ME', 'Mechanical Engineering'), ('CE', 'Civil Engineering'), ('EE', 'Electrical Engineering')]),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
