# Generated by Django 6.0.1 on 2026-02-11 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_submitassignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submitassignment',
            name='course_name',
        ),
        migrations.AddField(
            model_name='submitassignment',
            name='assignment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='assignments.assignment'),
            preserve_default=False,
        ),
    ]
